# .github/workflows/run_orgs.yml (draft)
name: GitGrowBot Org Refollower (Scheduled every 15 minutes)
# This workflow runs the GitGrowBot organization follow/refollow script on a schedule.
# It is triggered every 15 minutes via a cron job and can also be run manually.
# The script ensures the user follows or refollows target organizations to increase exposure.
# The follow and unfollow logic is separated into its own workflow to keep responsibilities clear.

on:
  # schedule:
    # - cron: '*/15 * * * *'    # every 15 minutes (UTC)
  workflow_dispatch:          # allow manual trigger

jobs:
  run-orgs:
    name: Run Org Refollow Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run organization follow/refollow
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python scripts/orgs.py