# .github/workflows/run_bot.yml
name: BotOla Follow Runner

# Only run when manually triggered
on:
  workflow_dispatch: {}

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyGithub
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run follow bot
        env:
          # your PAT_TOKEN must live here
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME_FILE: "usernames.txt"
          WHITELIST_FILE: "whitelist.txt"
          FOLLOWERS_PER_RUN: "10"
        run: python main.py
