# .github/workflows/run_bot.yml
name: GitGrowBot Scheduled Runner (Global)

on:
  schedule:
    - cron: '5 */1 * * *'
  workflow_dispatch: {}

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Unfollow non-reciprocals
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python scripts/unfollowers.py

      - name: Run follow bot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python scripts/gitgrow.py
