name: BotOla Follow Runner

on:
  schedule:
    - cron: '5 */3 * * *'    # every 3 hours at minute 5
  workflow_dispatch: {}

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyGithub
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run follow bot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME_FILE: "usernames.txt"
          WHITELIST_FILE: "whitelist.example.txt"
          FOLLOWERS_PER_RUN: "100"
        run: python scripts/bot_core.py
