# .github/workflows/stargazer_shoutouts.yml
name: GitGrowBot Stargazer Shoutouts (Manual)

on:
  workflow_dispatch:

jobs:
  stargazer_shoutouts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit and push changes

    steps:
      - name: Checkout tracker-data branch
        uses: actions/checkout@v4
        with:
          ref: tracker-data

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run shoutouts.py
        run: python3 scripts/shoutouts.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and push updated stars.json to tracker-data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update stargazers state [bot]"
          branch: tracker-data
          file_pattern: .github/state/stars.json
          # The action uses GITHUB_TOKEN by default.