# .github/workflows/stargazer_shoutouts.yml
name: GitGrowBot Stargazer Shoutouts (Scheduled)
# This workflow automatically welcomes new stargazers.
on:
  workflow_dispatch:

permissions:
  contents:    write   # allow committing updated JSON
  discussions: write   # allow posting to Discussions

jobs:
  shout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run shoutouts
        env:
          PAT_TOKEN:             ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY:     ${{ github.repository }}
          WELCOME_DISCUSSION_ID: ${{ vars.WELCOME_DISCUSSION_ID }}
        run: python scripts/shoutouts.py

      - name: Commit updated state
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/state/stars.json
          git diff --cached --quiet || git commit -m "chore: update stargazers state"
          git push
