# .github/workflows/stargazer_shoutouts.yml
name: GitGrowBot Stargazer Tracker (Manual Shoutouts)

on:
  workflow_dispatch:

jobs:
  stargazer_shoutouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run shoutouts.py
        run: python3 scripts/shoutouts.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload comment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stargazer-comments
          path: |
            .github/state/welcome_comments.md
            .github/state/farewell_comments.md
            .github/state/stars.json
