# .github/workflows/stargazer_shoutouts.yml
name: GitGrowBot Stargazer Shoutouts (Manual)

on:
  # This workflow is triggered manually and can also be run on a schedule.
  schedule:
    - cron: '55 11 * * *' # Runs daily at 11:55 UTC
  workflow_dispatch:

jobs:
  stargazer_shoutouts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit and push changes

    steps:
      - name: Checkout main/code branch
        uses: actions/checkout@v4
        # No ref, defaults to branch that triggered the workflow (main)

      - name: Fetch state file from tracker-data branch
        run: |
          git fetch origin tracker-data:tracker-data
          git checkout tracker-data -- .github/state/stars.json || true
          git checkout ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run shoutouts.py
        run: python3 scripts/shoutouts.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and push updated stars.json to tracker-data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update stargazers state [bot]"
          branch: tracker-data
          file_pattern: .github/state/stars.json

      - name: Upload shoutouts artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stargazer-comments
          path: |
            .github/state/welcome_comments.md
            .github/state/farewell_comments.md
            .github/state/stars.json
